id: P5237D7A2
initial_creation_type: input
source_metadata:
  title: Shikpo Lingpa Series
  language: bo
  description: 'Texts by the treasure revealer Shikpo Lingpa Gargyi Wangchuk Tsal
    (zhig po gling pa gar gyi dbang phyug rtsal, 1524–1583):'
  volume:
    94040ca989b04a929c326ea2d94aaf80:
      title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in
        the Union of Generation and Completion'
      parent: Sādhanas
created_at: '2022-03-01T01:37:19.487825'
last_modified_at: '2022-03-01T01:37:19.487828'
